//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientManagerNotifier.ClientManagerServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ClientManagerServiceReference.ILettersCheckService")]
    public interface ILettersCheckService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILettersCheckService/CheckForNewLetters", ReplyAction="http://tempuri.org/ILettersCheckService/CheckForNewLettersResponse")]
        int CheckForNewLetters(string userName, string passwordHash);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILettersCheckServiceChannel : ClientManagerNotifier.ClientManagerServiceReference.ILettersCheckService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LettersCheckServiceClient : System.ServiceModel.ClientBase<ClientManagerNotifier.ClientManagerServiceReference.ILettersCheckService>, ClientManagerNotifier.ClientManagerServiceReference.ILettersCheckService {
        
        public LettersCheckServiceClient() {
        }
        
        public LettersCheckServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LettersCheckServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LettersCheckServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LettersCheckServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int CheckForNewLetters(string userName, string passwordHash) {
            return base.Channel.CheckForNewLetters(userName, passwordHash);
        }
    }
}
